build: remove redhat builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -200,73 +200,73 @@ jobs:
           extra_build_args: |
             GOLANG_VERSION=${{ needs.get-go-version.outputs.go-version }}
 
-  build-docker-redhat:
-    name: Docker UBI Image Build (for Red Hat Certified Container Registry)
-    needs:
-      - get-go-version
-      - set-product-version
-      - build-linux
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        include:
-          - { target-name: "release-ubi", registry-id: "631f805e0d15f623c5996c2e" }
-    env:
-      repo: ${{github.event.repository.name}}
-      version: ${{needs.set-product-version.outputs.product-version}}
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      - uses: hashicorp/actions-docker-build@76d2fc91532d816ca2660d8f3139e432ac3700fd
-        with:
-          version: ${{env.version}}
-          target: ${{ matrix.target-name }}
-          arch: amd64
-          redhat_tag: quay.io/redhat-isv-containers/${{matrix.registry-id}}:${{env.version}}-ubi
+  # build-docker-redhat:
+  #   name: Docker UBI Image Build (for Red Hat Certified Container Registry)
+  #   needs:
+  #     - get-go-version
+  #     - set-product-version
+  #     - build-linux
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - { target-name: "release-ubi", registry-id: "631f805e0d15f623c5996c2e" }
+  #   env:
+  #     repo: ${{github.event.repository.name}}
+  #     version: ${{needs.set-product-version.outputs.product-version}}
+  #   steps:
+  #     - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+  #     - uses: hashicorp/actions-docker-build@76d2fc91532d816ca2660d8f3139e432ac3700fd
+  #       with:
+  #         version: ${{env.version}}
+  #         target: ${{ matrix.target-name }}
+  #         arch: amd64
+  #         redhat_tag: quay.io/redhat-isv-containers/${{matrix.registry-id}}:${{env.version}}-ubi
 
-  build-docker-ubi-dockerhub:
-    name: Docker ${{ matrix.arch }} UBI build for DockerHub
-    needs:
-      - get-go-version
-      - set-product-version
-      - build-linux
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        include:
-          - { arch: "amd64" }
-    env:
-      repo: ${{ github.event.repository.name }}
-      version: ${{ needs.set-product-version.outputs.product-version }}
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      # This naming convention will be used ONLY for per-commit dev images
-      - name: Set docker dev tag
-        run: |
-          echo "full_dev_tag=${{ env.version }}"
-          echo "full_dev_tag=${{ env.version }}" >> $GITHUB_ENV
-          echo "minor_dev_tag=$(echo ${{ env.version }}| sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+(-[0-9a-zA-Z\+\.]+)?$/\1\2/')" 
-          echo "minor_dev_tag=$(echo ${{ env.version }}| sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+(-[0-9a-zA-Z\+\.]+)?$/\1\2/')" >> $GITHUB_ENV
+  # build-docker-ubi-dockerhub:
+  #   name: Docker ${{ matrix.arch }} UBI build for DockerHub
+  #   needs:
+  #     - get-go-version
+  #     - set-product-version
+  #     - build-linux
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - { arch: "amd64" }
+  #   env:
+  #     repo: ${{ github.event.repository.name }}
+  #     version: ${{ needs.set-product-version.outputs.product-version }}
+  #   steps:
+  #     - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+  #     # This naming convention will be used ONLY for per-commit dev images
+  #     - name: Set docker dev tag
+  #       run: |
+  #         echo "full_dev_tag=${{ env.version }}"
+  #         echo "full_dev_tag=${{ env.version }}" >> $GITHUB_ENV
+  #         echo "minor_dev_tag=$(echo ${{ env.version }}| sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+(-[0-9a-zA-Z\+\.]+)?$/\1\2/')" 
+  #         echo "minor_dev_tag=$(echo ${{ env.version }}| sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+(-[0-9a-zA-Z\+\.]+)?$/\1\2/')" >> $GITHUB_ENV
 
-      - name: Docker Build (Action)
-        uses: hashicorp/actions-docker-build@76d2fc91532d816ca2660d8f3139e432ac3700fd
-        with:
-          smoke_test: |
-            TEST_VERSION="$(docker run "${IMAGE_NAME}" version | head -n1 | cut -d' ' -f2 | sed 's/^v//')"
-            if [ "${TEST_VERSION}" != "${version}" ]; then
-              echo "Test FAILED: Got ${TEST_VERSION}, want ${version}}."
-              exit 1
-            fi
-            echo "Test PASSED"
-          version: ${{ env.version }}
-          target: release-ubi
-          arch: ${{ matrix.arch }}
-          tags: |
-            docker.io/hashicorp/${{env.repo}}:${{env.version}}-ubi
-            public.ecr.aws/hashicorp/${{env.repo}}:${{env.version}}-ubi
-          dev_tags: |
-            docker.io/hashicorppreview/${{ env.repo }}:${{ env.full_dev_tag }}-ubi
-            docker.io/hashicorppreview/${{ env.repo }}:${{ env.full_dev_tag }}-ubi-${{ github.sha }}
-            docker.io/hashicorppreview/${{ env.repo }}:${{ env.minor_dev_tag }}-ubi
-            docker.io/hashicorppreview/${{ env.repo }}:${{ env.minor_dev_tag }}-ubi-${{ github.sha }}
+  #     - name: Docker Build (Action)
+  #       uses: hashicorp/actions-docker-build@76d2fc91532d816ca2660d8f3139e432ac3700fd
+  #       with:
+  #         smoke_test: |
+  #           TEST_VERSION="$(docker run "${IMAGE_NAME}" version | head -n1 | cut -d' ' -f2 | sed 's/^v//')"
+  #           if [ "${TEST_VERSION}" != "${version}" ]; then
+  #             echo "Test FAILED: Got ${TEST_VERSION}, want ${version}}."
+  #             exit 1
+  #           fi
+  #           echo "Test PASSED"
+  #         version: ${{ env.version }}
+  #         target: release-ubi
+  #         arch: ${{ matrix.arch }}
+  #         tags: |
+  #           docker.io/hashicorp/${{env.repo}}:${{env.version}}-ubi
+  #           public.ecr.aws/hashicorp/${{env.repo}}:${{env.version}}-ubi
+  #         dev_tags: |
+  #           docker.io/hashicorppreview/${{ env.repo }}:${{ env.full_dev_tag }}-ubi
+  #           docker.io/hashicorppreview/${{ env.repo }}:${{ env.full_dev_tag }}-ubi-${{ github.sha }}
+  #           docker.io/hashicorppreview/${{ env.repo }}:${{ env.minor_dev_tag }}-ubi
+  #           docker.io/hashicorppreview/${{ env.repo }}:${{ env.minor_dev_tag }}-ubi-${{ github.sha }}
 
   # TODO: Integration Test Here
